from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from app.services.ai.factory import get_ai_provider
from app.services.ai.base import AIResponse

class GeneratedTestCase(BaseModel):
    """A single test case generated by AI"""
    title: str = Field(..., description="Concise title of the test case")
    type: str = Field(..., description="Test type: Positive, Negative, Boundary, Security, Performance")
    priority: str = Field(..., description="Priority: High, Medium, Low")
    preconditions: List[str] = Field(default_factory=list, description="Steps to set up the test state")
    steps: List[str] = Field(..., description="Sequential steps to execute the test")
    expected_result: str = Field(..., description="The expected outcome of the test")
    rationale: str = Field(..., description="Why this test case is necessary based on the requirement")
    mapped_ac: List[str] = Field(default_factory=list, description="List of Acceptance Criteria IDs this test covers")

class TestGenerationResult(BaseModel):
    """The result of the AI test generation process"""
    test_cases: List[GeneratedTestCase] = Field(default_factory=list)
    coverage_summary: str = Field(..., description="Summary of how the generated tests cover the requirement")
    suggestions: List[str] = Field(default_factory=list, description="Suggestions for manual tests that AI might have missed")

class TestGenerationService:
    """
    Service responsible for generating manual test cases from requirements using AI.
    Generates tests as drafts to ensure human-in-the-loop control.
    """

    def __init__(self):
        self.ai_provider = get_ai_provider()

    async def generate_tests(
        self, 
        requirement_text: str, 
        acceptance_criteria: List[str], 
        context: Dict[str, Any] = None
    ) -> TestGenerationResult:
        """
        Generates a set of manual test cases based on a requirement and its ACs.
        """
        system_instruction = (
            "You are an expert QA Automation Engineer and Manual Tester. Your goal is to generate "
            "comprehensive manual test cases from software requirements. "
            "For every requirement, you must provide:\n"
            "1. Positive Tests: Verify the 'happy path' and expected behavior.\n"
            "2. Negative Tests: Verify how the system handles invalid input or unexpected behavior.\n"
            "3. Boundary Tests: Verify edge cases and limit values.\n"
            "4. Security/Performance Tests: If applicable, verify basic security or performance constraints.\n\n"
            "All tests must be detailed, executable, and mapped to specific Acceptance Criteria (AC). "
            "The output must be a structured list of test cases."
        )

        ac_formatted = "\n".join([f"- {ac}" for ac in acceptance_criteria])
        prompt = (
            f"Requirement:\n{requirement_text}\n\n"
            f"Acceptance Criteria:\n{ac_formatted}"
        )
        
        if context:
            prompt += f"\n\nAdditional Context:\n{context}"

        # Use structured data generation to get a TestGenerationResult
        response = await self.ai_provider.generate_structured_data(
            prompt=prompt,
            system_instruction=system_instruction,
            response_model=TestGenerationResult
        )

        import json
        try:
            data = json.loads(response.content)
            return TestGenerationResult(**data)
        except Exception:
            # Fallback for mock or malformed responses
            return TestGenerationResult(
                test_cases=[],
                coverage_summary="Test generation failed or returned non-JSON content.",
                suggestions=["Please manually define test cases for this requirement."]
            )
